
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    
  db:
    image: neo4j:5.5.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/passw0rd
      NEO4J_server_http_listen__address: db:7474
      NEO4J_server_bolt_listen__address: db:7687
    healthcheck:
      test: ["CMD-SHELL", "/var/lib/neo4j/bin/neo4j status"]
      # interval: 45s
      timeout: 5s
      retries: 7
      start_period: 2s
    volumes:
      - .volumes/neo4j/data:/data
      - .volumes//neo4j/logs:/logs
      - .volumes//neo4j/import:/var/lib/neo4j/import
      - .volumes//neo4j/plugins:/plugins
    # restart: always
